## YAML Template.
---
server:
    port: ${SERVER_PORT:5454}
    api-base-url: /api/v1
    max-http-header-size: 32768


spring:
    h2:
        console:
            path: /h2
            enabled: true
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                jdbc.lob.non_contextual_creation: true #HHH-12368
        hibernate:
            ddl-auto: none
    jackson:
        serialization:
            indent_output: true